f5index/urls.py
from django.urls import path
from . import views

app_name = 'f5index'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('recruiting/', views.recruiting, name='recruiting'),
    path('tours/', views.tours, name='tours'),
    path('nutrition/', views.nutrition, name='nutrition'),
    path('training/', views.training, name='training'),
    path('club-mgmt/', views.club_mgmt, name='club-mgmt'),
    path('services/', views.services, name='services'),
]

firstfive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('f5index.urls')),
    path('', include('store.urls')),
    path('', include('submissions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('store/', views.store, name='store'),
    path('store/category/', views.products_by_category, name='products_by_category'),
    path('store/products/<int:product_id>/', views.product_details, name='product_details'),
    path('store/products/purchase/<int:product_id>/', views.purchase, name='purchase'),
    path('store/products/purchase/success/', views.success, name='payment_success'),
    path('store/products/purchase/webhook_success/', views.stripe_webhook_payment_success, name='webhook_payment_success'),
]

submissions/urls.py
from django.urls import path
from . import views

app_name = 'submissions'
urlpatterns = [
    path('submission/recruiting/', views.handle_recruiting_submissions, name='recruiting_submission'),
    path('submission/tours/', views.handle_tours_submissions, name='tours_submission'),
    path('submission/team-item/', views.handle_team_item_submissions, name='team_item_submission'),
    path('submission/issue/', views.handle_issue_submission, name='issue'),
    path('submission/feedback/', views.handle_feedback_submission, name='feedback'),
    path('submission/design/', views.handle_design_submission, name='design'),
    path('submission/specialist/', views.handle_specialist_submission, name='specialist'),
    path('success/<str:message>/', views.success_page, name='success'),
]

f5index/models.py
from django.db import models

f5index/views.py
from django.shortcuts import render
from plans.models import PlayerPlan

def home(request):
    return render(request, 'f5index/index.html')

def about(request):
    return render(request, 'f5index/about.html')

def store(request):
    return render(request, 'f5index/store.html')

def recruiting(request):
    return render(request, 'f5index/recruiting.html')

def tours(request):
    return render(request, 'f5index/tours.html')

def nutrition(request):
    return render(request, 'f5index/nutrition.html')

def training(request):
    return render(request, 'f5index/training.html')

def club_mgmt(request):
    return render(request, 'f5index/club_mgmt.html')

def services(request):
    plans = PlayerPlan.objects.all()
    
    context = {
        'plans': plans,
    }
    return render(request, 'f5index/services.html', context)

firstfive/templates/f5index/about.html
{% extends 'base.html' %}

{% block title %} About page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Learn about First Five Rugby, the dedicated platform for rugby enthusiasts in North America. Read our story, mission, and how we're enriching the rugby community.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock %}

{% block content %}
<section class="welcome-section">
    <div class="container">
        <div class="welcome-wrapper">
            <p class="welcome-title">Welcome to First Five Rugby</p>
            <p class="welcome-statement">We are the premier online destination dedicated to fostering and enriching the rugby community. Conceived and crafted with passion by the community, this platform serves as a comprehensive guide and resource hub for enthusiasts, players, coaches, referees, and parents involved in the sport.</p>
        </div>

        <div class="scroll-action">
            <p>For all your rugby needs.</p>
            <p><i class="fa-solid fa-angle-down"></i></p>
        </div>
    </div>
</section>

<div class="row-wrapper">
    <!-- First Section: Comprehensive Rugby Hub -->
    <section class="diverse-section">
        <div class="content">
            <h2>Comprehensive Rugby Hub</h2>
            <p>Explore rugby education, coaching, player guidance, and updates on our platform. From basics to advanced tactics, skill enhancement, and the latest news.</p>
        </div>
        <div class="action-wrapper">
            <div class="action-link-wrapper">
                <a class="action-link" href="{% url 'f5index:services' %}"><i class="fa-brands fa-hubspot"></i></a>
            </div>
        </div>
    </section>

    <!-- Second Section: Complete Rugby Apparel -->
    <section class="store-section">
        <div class="content">
            <h2>Complete Rugby Apparel</h2>
            <p>Discover diverse rugby apparel and tailored services at First Five Rugby, ensuring a complete rugby experience.</p>
        </div>
        <div class="action-wrapper">
            <div class="action-link-wrapper">
                <a class="action-link" href="{% url 'store:store' %}"><i class="fa-solid fa-store"></i></a>
            </div>
        </div>
    </section>

    <!-- Third Section: Join Our Growing Community -->
    <section class="community-section">
        <div class="content">
            <h2>Join Our Growing Community</h2>
            <p>Pioneer a rugby community beyond a website. Engage, learn, and make a difference at First Five Rugby. Your passion, our home.</p>
        </div>
        <div class="action-wrapper">
            <div class="action-link-wrapper">
                <a class="action-link" target="_blank" href="https://www.instagram.com/firstfiverugby"><i class="fa-brands fa-instagram"></i></a>
            </div>
        </div>
    </section>
</div>

{% endblock %}

firstfive/templates/f5index/club_mgmt.html
{% extends 'base.html' %}

{% block title %} Club Mgmt Page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="We offer services for clubs, including creating a 501c3, recruiting plans, and social media management.">
    <link rel="stylesheet" href="{% static 'css/club-mgmt.css' %}">
{% endblock %}

{% block content %}
<div class="banner" >
    <div class="container">
        <div class="banner-section">
            <div class="title-wrapper">
                <h1 class="banner-title">Club Management</h1>
                <p class="banner-subtitle"></p>
            </div>
        </div>
    </div>
</div>



<section class="statement-section">
    <div class="container">
        <div class="statement-wrapper">
            <p class="statement-title">Manage</p>
            <h2 class="statement">
                Effective club management is vital for player success and club longevity. We provide services such as creating a 501c3 fund, managing social media, and recruiting to support clubs in achieving their goals both on and off the field.
            </h2>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/f5index/index.html
{% extends 'base.html' %}

{% block title %} Home page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Discover First Five Rugby - your gateway to the North American rugby community. Explore resources, news, and insights into the world of rugby. Join us and fuel your passion for the sport.">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="{% static 'js/slider.js'%}"></script>
{% endblock %}

{% block content %}
<section class="jumbotron" style="background-image: url('{% static 'media/index/main-bg.jpg' %}')">
    <div class="jumbo-container">
        <div class="slider-container">
            <div class="slide-wrapper">
                <a class="slide-link" href="{% url 'store:store' %}">
                    <img class="slide-img" src="{% static 'media/index/slide_customs.jpg' %}" />
                </a>
            </div>
            <div class="slide-wrapper">
                <a class="slide-link" href="{% url 'store:store' %}">
                    <img class="slide-img" src="{% static 'media/index/slide_vintage.jpg' %}" />
                </a>
            </div>
            <div class="slide-wrapper">
                <a class="slide-link" href="{% url 'store:store' %}">
                    <img class="slide-img" src="{% static 'media/index/slide_deals.jpg' %}" />
                </a>
            </div>
        </div>
        <div class="action-container">
            <div class="action-list">
                <a class="action-link" href="{% url 'f5index:recruiting' %}">
                    <div class="link-wrap">
                        <div class="text">Play / Study Abroad</div>
                        <div class="icon"><i class="fa-solid fa-school-flag"></i></div>
                    </div>
                </a>
                <a class="action-link" href="{% url 'f5index:tours' %}">
                    <div class="link-wrap">
                        <div class="text">Ireland Team Tours</div>
                        <div class="icon"><i class="fa-solid fa-plane-departure"></i></div>
                    </div>
                </a>
                <a class="action-link" href="{% url 'f5index:services' %}">
                    <div class="link-wrap">
                        <div class="text">Training / Meal Plans</div>
                        <div class="icon"><i class="fa-solid fa-bowl-food"></i></div>
                    </div>
                </a>
                <a class="action-link" href="{% url 'f5index:club-mgmt' %}">
                    <div class="link-wrap">
                        <div class="text">Rugby Club MGMT</div>
                        <div class="icon"><i class="fa-solid fa-people-group"></i></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>
<section class="abroad-section" style="background-image: url('{% static 'media/index/abroad-bg.jpg' %}')">
    <div class="container">
        <div class="schools-wrapper">
            <h1 class="schools-title">Top UK Schools Welcome American Students</h1>
            <p class="subtitle">Create your own pro pathway with an amazing education.</p>
            <div class="schools-stats">
                <div class="stat">
                    <h1 class="number">5</h1>
                    <p class="label">Unique Countries</p>
                </div>
                <div class="stat">
                    <h1 class="number">8</h1>
                    <p class="label">Top Schools</p>
                </div>
            </div>
        </div>
        <div class="schools-action-wrapper">
            <p class="action-tagline">*Guarantee call-back within 24 hours of request.</p>
            <a class="link-button" href="{% url 'f5index:recruiting' %}">Scholarships Available</a>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/f5index/nutrition.html
{% extends 'base.html' %}

{% block title %} Nutrition page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="We offer free nutrition plans and paid services from experts in rugby and performance nutrition.">
    <link rel="stylesheet" href="{% static 'css/nutrition.css' %}">
{% endblock %}

{% block content %}
<div class="banner" >
    <div class="container">
        <div class="banner-section">
            <div class="title-wrapper">
                <h1 class="banner-title">Nutrition</h1>
                <p class="banner-subtitle"></p>
            </div>
        </div>
    </div>
</div>
<section class="statement-section">
    <div class="container">
        <div class="statement-wrapper">
            <p class="statement-title">Food</p>
            <h2 class="statement">Food is a cornerstone of sports performance, but it's a challenge to get it right. Yet, the rewards are immense, impacting endurance, strength, and well-being. We offer free nutritional guides for athletes, recognizing their unique needs. Soon, we'll provide one-on-one meetings with experts for personalized advice and meal plans, ensuring each athlete reaches their full potential.</h2>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/f5index/recruiting.html
{% extends 'base.html' %}

{% block title %} Recruiting Page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Embark on an unparalleled rugby adventure! Our program offers players the unique opportunity to study and play in top rugby nations like the USA, Ireland, Scotland, and England. Elevate your skills and education on an international stage.">
    <link rel="stylesheet" href="{% static 'css/recruiting.css' %}">
    <script src="{% static 'js/modal.js'%}"></script>
{% endblock %}

{% block content %}
<section class="selection-section">
    <div class="container">
        <div class="roles-container">
            <h1 class="roles-title">Follow your own <span class="highlight">pro pathway</span> and get a great education.</h1>
            <a class="apply-button" href="{% url 'submissions:recruiting_submission' %}">Scholarships Available</a>
            <div class="roles-wrapper">
                <div class="role">
                    <div class="role-meta">
                        <h3 class="country-name">USA</h3>
                    </div>
                    <div class="country-wrapper">
                        <img class="country_img" src="{% static 'media/recruiting/usa.png' %}" />
                    </div>
                </div>
                <div class="role">
                    <div class="role-meta">
                        <h3 class="country-name">England</h3>
                    </div>
                    <div class="country-wrapper">
                        <img class="country_img" src="{% static 'media/recruiting/uk.png' %}" />
                    </div>
                </div>
                <div class="role">
                    <div class="role-meta">
                        <h3 class="country-name">Scotland</h3>
                    </div>
                    <div class="country-wrapper">
                        <img class="country_img" src="{% static 'media/recruiting/sct.png' %}" />
                    </div>
                </div>
                <div class="role">
                    <div class="role-meta">
                        <h3 class="country-name">Ireland</h3>
                    </div>
                    <div class="country-wrapper">
                        <img class="country_img" src="{% static 'media/recruiting/ire.png' %}" />
                    </div>
                </div>
                <div class="role">
                    <div class="role-meta">
                        <h3 class="country-name">Wales</h3>
                    </div>
                    <div class="country-wrapper">
                        <img class="country_img" src="{% static 'media/recruiting/wal.png' %}" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="info-section">
    <div class="container">
        <div class="info-container">
            <h1 class="title">Pathway</h1>
            <p class="info-subtitle">Travel. Study. Excel.</p>
            <p class="info-summary">First Five Rugby recruiting has over 25 years of experience placing athletes in international and top ranked programs with a direct pathway to a professional club - resulting in students furthering their education while also getting the opportunity to test their abilities in a world class environment.</p>
        </div>
    </div>
</section>

<section class="age-section">
    <div class="sm-container">
        <div class="age-section-wrapper">
            <h1 class="title age">Explore all the options.</h1>
        </div>
        <div class="levels-section-wrapper">
            <div class="level-wrapper">
                <div class="level-image">
                    <img src="{% static 'media/recruiting/highschool.jpg' %}" alt="highschool photo"/>
                </div>
                <div class="level-desc">
                    <h3>High School</h3>
                    <p>High school aged students to attend school and play rugby at multiple English, Scottish, Welsh, and Irish schools.</p>
                    <a class="level apply-button float-right" href="{% url 'submissions:recruiting_submission' %}">Apply Now</a>
                </div>
            </div>
            <div class="level-wrapper order-secondary">
                <div class="level-desc secondary">
                    <h3>College</h3>
                    <p>University aged students to attend school and play rugby at top American Universities in the United States.</p>
                    <a class="level apply-button" href="{% url 'submissions:recruiting_submission' %}">Apply Now</a>
                </div>
                <div class="level-image">
                    <img src="{% static 'media/recruiting/college.jpg' %}" alt="highschool photo"/>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

firstfive/templates/f5index/services.html
{% extends 'base.html' %}

{% block title %} Services page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Explore our bespoke rugby services at First Five Rugby. From club support to player development, we offer tailored solutions to elevate your rugby experience.">
    <link rel="stylesheet" href="{% static 'css/services.css' %}">
    <script src="{% static 'js/service-marquees.js'%}"></script>
{% endblock %}

{% block content %}
<div class="nav-spacer">
</div>
<div class="section section-hero theme-dark">
    <div class="section-content">
        <div class="hero-headline">Meet the<br class="small"> A-list of<br> rugby services.</div>
        <div class="copy-wrapper">
            <div class="hero-tagline">Unlock elite fitness plans, tailored diets, premier rugby gear, and exclusive opportunities. Elevate your game and lifestyle with us. The ultimate rugby experience lives here—only on First Five Rugby.</div>
        </div>
    </div>
</div>
<div class="section-content">
    <div class="banner-wrapper">
        <div class="banner-icon">
            <img src="{% static 'media/index/firstfive-logo.png' %}" />
        </div>
        <div class="banner-content">Get help from an expert on <br class="small"> any service with one call.</div>
        <div class="banner-link">
            <a href="#">Learn more</a>
        </div>
    </div>
</div>
<div class="section-content video-hero">
    <div class="video-wrapper">
        <video class="video" autoplay muted loop playsinline>
            <source src="{% static 'media/services/service-hero.mp4' %}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
    </div>
    <div class="hero-heading-content">
        <div class="hero-heading-headline">
            Access game-winning<br>rugby plans for<br class="small"> gym & diet.
        </div>
        <div class="hero-heading-cta-container">
            <div class="banner-link hero-video-link">
                <a class="theme-light text-dark" href="#">Free plans</a>
            </div>
            <div class="banner-link hero-video-link">
                <a href="#">Learn more</a>
            </div>
        </div>
    </div>
</div>
<div class="dynamic-gallery marquees-container">
    <div class="dynamic-gallery-item-container">
        <div id="dynamic-gallery-item-a">
            <div class="marquees images-loading">
                <ul class="marquees-list">
                    {% for plan in plans %}
                        <li class="marquees-tile">
                            <a class="marquees-link" href="#">
                                <div class="plan-image">
                                    <img src="{{ plan.plan_picture.url }}" />
                                </div>
                                <div class="plan-title">{{ plan.plan_name }}</div>
                                <div class="plan-category">{{ plan.plan_category }}</div>
                            </a>
                        </li>
                        {% empty %}
                        <li class="marquees-tile">
                            <a class="marquees-link" href="#">
                                <div class="plan-title">No plans found.</div>
                                <div class="plan-category">Empty</div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
<section class="services-section">
    <div class="services-container">
        <div class="services-wrapper">
            <div class="service">
                <p class="service-title">Strength & Conditioning</p>
                <p class="service-statement">Free fitness resources crafted by experts. One-on-ones available soon.</p>
                <a class="service-link" href="{% url 'f5index:training' %}">Free Plans >></a>
            </div>
            <div class="service">
                <p class="service-title">Player Nutrition</p>
                <p class="service-statement">Free nutritional guides created by experts. One-on-ones available soon.</p>
                <a class="service-link" href="{% url 'f5index:nutrition' %}">Free Plans >></a>
            </div>
            <div class="service">
                <p class="service-title">Team Tours</p>
                <p class="service-statement">Custom tour of Ireland for your rugby club. Stay in numerous cities, explore historic Ireland.</p>
                <a class="service-link" href="{% url 'f5index:tours' %}">Free Quote >></a>
            </div>
            <div class="service">
                <p class="service-title">Study & Play Abroad</p>
                <p class="service-statement">We provide direct connections to top schools and pro clubs.</p>
                <a class="service-link" href="{% url 'f5index:recruiting' %}">Scholarships >></a>
            </div>
            <div class="service">
                <p class="service-title">Club Management</p>
                <p class="service-statement">Let experts manage your funding, social media, and recruiting.</p>
                <a class="service-link" href="{% url 'f5index:club-mgmt' %}">Free Consultation >></a>
            </div>
            <div class="service">
                <p class="service-title">Rugby Store</p>
                <p class="service-statement">Shop vintage jerseys, custom team wear, and daily deals.</p>
                <a class="service-link" href="{% url 'store:store' %}">Daily Deals >></a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/f5index/tours.html
{% extends 'base.html' %}

{% block title %} Tours page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Learn about First Five Rugby, the dedicated platform for rugby enthusiasts in North America. Read our story, mission, and how we're enriching the rugby community.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/tours.css' %}">
{% endblock %}

{% block content %}
<section class="tours-section">
    <div class="container">
        <div class="ireland-wrapper">
            <p class="ireland-preface">Dreams come true in ireland.  Explore the country - on the pitch and in the town with known irish clubs. Get a free team quote. We call back within 48 hours.</p>
            <h1 class="ireland-title">IRELAND</h1>
        </div>
    </div>
</section>
<section class="partners-section">
    <div class="container">
        <h1 class="section-title">Our Partners</h1>
        <div class="partners-wrapper">
            <div class="sponsor">
                <img class="sponsor-img" src="{% static 'media/tours/sponsor-01.png' %}" />
                <h2 class="sponsor-name">emerald escapes</h2>
            </div>
            <div class="sponsor">
                <img class="sponsor-img" src="{% static 'media/tours/sponsor-02.png' %}" />
                <h2 class="sponsor-name">globetrotter</h2>
            </div>
            <div class="sponsor">
                <img class="sponsor-img" src="{% static 'media/tours/sponsor-03.png' %}" />
                <h2 class="sponsor-name">wunderlust</h2>
            </div>
        </div>
    </div>
</section>
<section class="action-section">
    <div class="container">
        <div class="action-wrapper">
            <h2 class="action-title">Travel To Ireland.</h2>
            <h1 class="action-caption">Forget the Rest and Book With Us.</h1>
            <a class="action-button" href="{% url 'submissions:tours_submission' %}">Get a Free Quote</a>
        </div>
        <div class="preview-wrapper">
            <div class="preview">
                <img class="preview-img" src="{% static 'media/tours/ireland-01.jpg' %}" />
                <p>Visit and stay overnight in cities like Galway, Clifden, Cork, Kilkenny, Kerry, Dublin. Breakfast included.</p>
            </div>
            <div class="preview">
                <img class="preview-img" src="{% static 'media/tours/ireland-02.jpg' %}" />
                <p>Watch pro matches and get exclusive behind the scenes tour. Fixtures have included Shannon, Munster, Connacht, Rockwell..</p>
            </div>
            <div class="preview">
                <img class="preview-img" src="{% static 'media/tours/ireland-03.jpg' %}" />
                <p>Explore historic ireland locations, guided by our trusted bus drivers that know the area best.</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/f5index/training.html
{% extends 'base.html' %}

{% block title %} Training page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="We offer free training plans and paid services from experts in strength and conditioning.">
    <link rel="stylesheet" href="{% static 'css/training.css' %}">
{% endblock %}

{% block content %}
<div class="banner" >
    <div class="container">
        <div class="banner-section">
            <div class="title-wrapper">
                <h1 class="banner-title">Strength & Conditioning</h1>
                <p class="banner-subtitle"></p>
            </div>
        </div>
    </div>
</div>
<section class="statement-section">
    <div class="container">
        <div class="statement-wrapper">
            <p class="statement-title">Body</p>
            <h2 class="statement">
                Strength and conditioning are essential for rugby players, influencing performance and injury prevention. We'll soon offer free training plans and one-on-one sessions with experts to help players optimize their training and excel on the field.
            </h2>
        </div>
    </div>
</section>
{% endblock %}