firstfive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('f5index.urls')),
    path('', include('store.urls')),
    path('', include('submissions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('store/', views.store, name='store'),
    path('store/category/', views.products_by_category, name='products_by_category'),
    path('store/products/<int:product_id>/', views.product_details, name='product_details'),
    path('store/products/purchase/<int:product_id>/', views.purchase, name='purchase'),
    path('store/products/purchase/success/', views.success, name='payment_success'),
    path('store/products/purchase/webhook_success/', views.stripe_webhook_payment_success, name='webhook_payment_success'),
]

submissions/urls.py
from django.urls import path
from . import views

app_name = 'submissions'
urlpatterns = [
    path('submission/recruiting/', views.handle_recruiting_submissions, name='recruiting_submission'),
    path('submission/tours/', views.handle_tours_submissions, name='tours_submission'),
    path('submission/team-item/', views.handle_team_item_submissions, name='team_item_submission'),
    path('submission/issue/', views.handle_issue_submission, name='issue'),
    path('submission/feedback/', views.handle_feedback_submission, name='feedback'),
    path('submission/design/', views.handle_design_submission, name='design'),
    path('submission/specialist/', views.handle_specialist_submission, name='specialist'),
    path('success/<str:message>/', views.success_page, name='success'),
]

submissions/models.py
from django.db import models
from django.core.validators import MinValueValidator
from .choices import STATUS_OPTIONS, COUNTRY_OPTIONS, TEAM_ITEM_OPTIONS

class BaseSubmissionModel(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    email = models.CharField(max_length=150)
    phone = models.CharField(max_length=150)
    status = models.CharField(choices=STATUS_OPTIONS, max_length=20, default='Unseen')

    class Meta:
        abstract = True

class RecruitingSubmission(BaseSubmissionModel):
    position = models.CharField(max_length=50, default='prop')
    age = models.IntegerField(default="12", validators=[MinValueValidator(12),])
    origin_country = models.CharField(max_length=50, default='usa')
    destination_country = models.CharField(choices=COUNTRY_OPTIONS, max_length=50, default='United States')

class ToursSubmission(BaseSubmissionModel):
    teamname = models.CharField(max_length=100, default='Firstfive RFC')
    teamsize = models.IntegerField(default="15", validators=[MinValueValidator(15),])

class CanterburyKitSubmission(BaseSubmissionModel):
    teamname = models.CharField(max_length=100, default='Firstfive RFC')
    teamsize = models.IntegerField(default="15", validators=[MinValueValidator(15),])

class TeamItemSubmission(BaseSubmissionModel):
    product_name = models.CharField(choices=TEAM_ITEM_OPTIONS, max_length=50, default='Rugby Caps')
    teamname = models.CharField(max_length=100, default='Firstfive RFC')
    team_primary_color = models.CharField(max_length=50, default='red')
    team_secondary_color = models.CharField(max_length=50, default='black')
    teamsize = models.IntegerField(default="15", validators=[MinValueValidator(15),])

class Issue(models.Model):
    email = models.EmailField()
    problem_description = models.TextField()
    status = models.CharField(choices=STATUS_OPTIONS, max_length=20, default='Unseen')

    def __str__(self):
        return f"Issue reported by {self.email}"
    
class Feedback(models.Model):
    email = models.EmailField()
    feedback = models.TextField()
    status = models.CharField(choices=STATUS_OPTIONS, max_length=20, default='Unseen')

    def __str__(self):
        return f"Feedback submitted by {self.email}"
    
class Design(models.Model):
    email = models.EmailField()
    design_description = models.TextField()
    status = models.CharField(choices=STATUS_OPTIONS, max_length=20, default='Unseen')

    def __str__(self):
        return f"Design submitted by {self.email}"

class Specialist(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    email = models.EmailField()
    cell = models.CharField(max_length=15)
    help_details = models.TextField()
    status = models.CharField(choices=STATUS_OPTIONS, max_length=20, default='Unseen')

    def __str__(self):
        return f"Specialist request submitted by {self.email}"

submissions/forms.py
from django import forms
from .models import RecruitingSubmission, ToursSubmission, CanterburyKitSubmission, TeamItemSubmission, Issue, Feedback, Design, Specialist

class RecruitingSubmissionForm(forms.ModelForm):
    class Meta:
        model = RecruitingSubmission
        exclude = ['status',]
        labels = {
            'firstname': 'First Name',
            'lastname': 'Last Name',
            'email': 'Email Address',
            'phone': 'Phone Number',
            'position': 'Position',
            'age': 'Age',
            'origin_country': 'Origin Country',
            'destination_country': 'Destination Country',
        }

class ToursSubmissionForm(forms.ModelForm):
    class Meta:
        model = ToursSubmission
        exclude = ['status',]
        labels = {
            'firstname': 'First Name',
            'lastname': 'Last Name',
            'email': 'Email Address',
            'phone': 'Phone Number',
            'teamname': 'Team Name',
            'teamsize': 'Team Size',
        }

class CanterburyKitSubmissionForm(forms.ModelForm):
    class Meta:
        model = CanterburyKitSubmission
        exclude = ['status',]
        labels = {
            'firstname': 'First Name',
            'lastname': 'Last Name',
            'email': 'Email Address',
            'phone': 'Phone Number',
            'teamname': 'Team Name',
            'teamsize': 'Team Size',
        }

class TeamItemSubmissionForm(forms.ModelForm):
    class Meta:
        model = TeamItemSubmission
        exclude = ['status']
        labels = {
            'product_name': 'Product Name',
            'firstname': 'First Name',
            'lastname': 'Last Name',
            'email': 'Email Address',
            'phone': 'Phone Number',
            'teamname': 'Team Name',
            'team_primary_color': 'Team Main Color',
            'team_seconday_color': 'Team Secondary Color',
            'teamsize': 'Team Size',
        }

class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        exclude = ['status']
        labels = {
            'email': 'Email',
            'problem_description': 'Problem Description',
        }

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = ['status']
        labels = {
            'email': 'Email',
            'feedback': 'Feedback',
        }

class DesignForm(forms.ModelForm):
    class Meta:
        model = Design
        exclude = ['status']
        labels = {
            'email': 'Email',
            'design_description': 'Design Description',
        }

class SpecialistForm(forms.ModelForm):
    class Meta:
        model = Specialist
        exclude = ['status']
        labels = {
            'firstname': 'First Name',
            'lastname': 'Last Name',
            'email': 'Email',
            'cell': 'Cell Phone',
            'help_details': 'Help Details',
        }

submissions/views.py
"""
Submissions Views
=================

This module contains view functions for handling various types of form submissions, including recruiting interest, tours interest, team item interest, issue reporting, feedback submission, design submission, and specialist help request.

Functions:
- handle_recruiting_submissions(request): Handles the submission of the study abroad interest form.
- handle_tours_submissions(request): Handles the submission of the tours interest form.
- handle_team_item_submissions(request): Handles the submission of the team item interest form.
- handle_issue_submission(request): Handles the submission of the issue reporting form.
- handle_feedback_submission(request): Handles the submission of the feedback form.
- handle_design_submission(request): Handles the submission of the design submission form.
- handle_specialist_submission(request): Handles the submission of the specialist help request form.
- success_page(request, message): Renders the success page with a success message.

"""

from django.shortcuts import redirect, render
from .forms import (
    RecruitingSubmissionForm, 
    ToursSubmissionForm, 
    TeamItemSubmissionForm, 
    IssueForm, 
    FeedbackForm, 
    DesignForm, 
    SpecialistForm
)

def handle_recruiting_submissions(request):
    """
    Renders the study abroad interest form and handles its submission.
    
    If the form is submitted via POST request and is valid, saves the form data and redirects to the success page.
    Otherwise, re-renders the form with validation errors.
    """
    title = 'Study Abroad Interest Form'
    form = RecruitingSubmissionForm()
    if request.method == 'POST':
        form = RecruitingSubmissionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('submissions:success', message='Your recruiting submission was successful')
        else:
            form = RecruitingSubmissionForm()

    context = {
        'form': form,
        'title': title,
    }
    return render(request, 'submissions/handle_recruiting_form.html', context)


def handle_tours_submissions(request):
    """
    Renders the tours interest form and handles its submission.
    
    If the form is submitted via POST request and is valid, saves the form data and redirects to the success page.
    Otherwise, re-renders the form with validation errors.
    """
    title = 'Tours Interest Form'
    form = ToursSubmissionForm()
    if request.method == 'POST':
        form = ToursSubmissionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('submissions:success', message='Your tours quote form has been submitted')
        else:
            form = ToursSubmissionForm()

    context = {
        'form': form,
        'title': title,
    }
    return render(request, 'submissions/handle_tours_form.html', context)


def handle_team_item_submissions(request):
    """
    Renders the team item interest form and handles its submission.
    
    If the form is submitted via POST request and is valid, saves the form data and redirects to the success page.
    Otherwise, re-renders the form with validation errors.
    """
    title = 'Team Item Interest Form'
    form = TeamItemSubmissionForm()

    if request.method == 'POST':
        form = TeamItemSubmissionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('submissions:success', message='Your team item form has been submitted')
        else:
            form = TeamItemSubmissionForm()  # Ensure form remains read-only

    context = {
        "form": form,
        "title": title,
    }
    return render(request, 'submissions/handle_team_item_form.html', context)


def handle_issue_submission(request):
    """
    Renders the issue reporting form and handles its submission.
    
    If the form is submitted via POST request and is valid, saves the form data and redirects to the success page.
    Otherwise, re-renders the form with validation errors.
    """
    title = 'Report an Issue'
    form = IssueForm()

    if request.method == 'POST':
        form = IssueForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('submissions:success', message='Your issue has been successfully reported')
        else:
            # Re-render the form with validation errors
            form = IssueForm(request.POST)

    context = {
        'form': form,
        'title': title,
    }
    return render(request, 'submissions/handle_issue_form.html', context)


def handle_feedback_submission(request):
    """
    Renders the feedback form and handles its submission.
    
    If the form is submitted via POST request and is valid, saves the form data and redirects to the success page.
    Otherwise, re-renders the form with validation errors.
    """
    title = 'Submit Feedback'
    form = FeedbackForm()

    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('submissions:success', message='Your feedback has been successfully submitted')
        else:
            # Re-render the form with validation errors
            form = FeedbackForm(request.POST)

    context = {
        'form': form,
        'title': title,
    }
    return render(request, 'submissions/handle_feedback_form.html', context)


def handle_design_submission(request):
    """
    Renders the design submission form and handles its submission.
    
    If the form is submitted via POST request and is valid, saves the form data and redirects to the success page.
    Otherwise, re-renders the form with validation errors.
    """
    title = 'Submit Design'
    form = DesignForm()

    if request.method == 'POST':
        form = DesignForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('submissions:success', message='Your design has been successfully submitted')
        else:
            # Re-render the form with validation errors
            form = DesignForm(request.POST)

    context = {
        'form': form,
        'title': title,
    }
    return render(request, 'submissions/handle_design_form.html', context)


def handle_specialist_submission(request):
    """
    Renders the specialist help request form and handles its submission.
    
    If the form is submitted via POST request and is valid, saves the form data and redirects to the success page.
    Otherwise, re-renders the form with validation errors.
    """
    title = 'Request Specialist Help'
    form = SpecialistForm()

    if request.method == 'POST':
        form = SpecialistForm(request.POST)
        if form.is_valid():
            form.save()
            message = "Your request for a specialist has been submitted. A member of our team will be in contact with you soon. Be sure to check your spam folder."
            return redirect('submissions:success', message=message)
        else:
            # Re-render the form with validation errors
            form = SpecialistForm(request.POST)

    context = {
        'form': form,
        'title': title,
    }
    return render(request, 'submissions/handle_specialist_form.html', context)


def success_page(request, message):
    """
    Renders the success page with a success message.
    """
    return render(request, 'submissions/success.html', {'message' : message})

firstfive/templates/submissions/handle_design_form.html
{% extends 'base.html' %}

{% block title %} Form page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="A form that allows users to submit a new product design idea on our platform.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/submission_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<section class="success-section">
    <div class="container">
        <div class="form-wrapper">
            <h1 class="form-title">{{title}}</h1>
            <form method="post" action="{% url 'submissions:design' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="button-wrapper">
                    <button class="submit-button" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/submissions/handle_feedback_form.html
{% extends 'base.html' %}

{% block title %} Form page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="A form that allows users to submit feedback on the site.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/submission_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<section class="success-section">
    <div class="container">
        <div class="form-wrapper">
            <h1 class="form-title">{{title}}</h1>
            <form method="post" action="{% url 'submissions:feedback' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="button-wrapper">
                    <button class="submit-button" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/submissions/handle_issue_form.html
{% extends 'base.html' %}

{% block title %} Form page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="A form that allows users to report issues on the site.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/submission_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<section class="success-section">
    <div class="container">
        <div class="form-wrapper">
            <h1 class="form-title">{{title}}</h1>
            <form method="post" action="{% url 'submissions:issue' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="button-wrapper">
                    <button class="submit-button" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/submissions/handle_recruiting_form.html
{% extends 'base.html' %}

{% block title %} Form page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="A success page to tell the user we have received their form submission.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/submission_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<section class="success-section">
    <div class="container">
        <div class="form-wrapper">
            <h1 class="form-title">{{title}}</h1>
            <form method="post" action="{% url 'submissions:recruiting_submission' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="button-wrapper">
                    <button class="submit-button" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/submissions/handle_specialist_form.html
{% extends 'base.html' %}

{% block title %} Form page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="A form that allows users to ask for for specialist support shopping help on our platform store.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/submission_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<section class="success-section">
    <div class="container">
        <div class="form-wrapper">
            <h1 class="form-title">{{title}}</h1>
            <form method="post" action="{% url 'submissions:specialist' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="button-wrapper">
                    <button class="submit-button" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/submissions/handle_submission_form.html
{% extends 'base.html' %}

{% block title %} Form page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="A success page to tell the user we have received their form submission.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/submission_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<section class="success-section">
    <div class="container">
        <div class="form-wrapper">
            <h1 class="form-title">{{title}}</h1>
            <form method="post" action="{% url 'submissions:recruiting_submission' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="button-wrapper">
                    <button class="submit-button" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/submissions/handle_team_item_form.html
{% extends 'base.html' %}

{% block title %} Form page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="A success page to tell the user we have received their form submission.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/submission_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<section class="success-section">
    <div class="container">
        <div class="form-wrapper">
            <h1 class="form-title">{{title}}</h1>
            <form method="post" action="{% url 'submissions:team_item_submission' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="button-wrapper">
                    <button class="submit-button" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/submissions/handle_tours_form.html
{% extends 'base.html' %}

{% block title %} Form page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="A success page to tell the user we have received their form submission.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/submission_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<section class="success-section">
    <div class="container">
        <div class="form-wrapper">
            <h1 class="form-title">{{title}}</h1>
            <form method="post" action="{% url 'submissions:tours_submission' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="button-wrapper">
                    <button class="submit-button" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

firstfive/templates/submissions/success.html
{% extends 'base.html' %}

{% block title %} Success page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="A success page to tell the user we have received their form submission.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/success.css' %}">
{% endblock %}

{% block content %}
<section class="success-section">
    <div class="container">
        <div class="success-wrapper">
            <h1>Success.</h1>
            <p>{{message}}</p>
            <p><em>'Thank you for everything you do'</em> -First Five Rugby</p>
        </p>
    </div>
</section>
{% endblock %}