f5index/urls.py
from django.urls import path
from . import views

app_name = 'f5index'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('recruiting/', views.recruiting, name='recruiting'),
    path('tours/', views.tours, name='tours'),
    path('nutrition/', views.nutrition, name='nutrition'),
    path('training/', views.training, name='training'),
    path('club-mgmt/', views.club_mgmt, name='club-mgmt'),
    path('services/', views.services, name='services'),
]

firstfive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('f5index.urls')),
    path('', include('store.urls')),
    path('', include('submissions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('store/', views.store, name='store'),
    path('store/category/', views.products_by_category, name='products_by_category'),
    path('store/products/<int:product_id>/', views.product_details, name='product_details'),
    path('store/products/purchase/<int:product_id>/', views.purchase, name='purchase'),
    path('store/products/purchase/success/', views.success, name='payment_success'),
    path('store/products/purchase/webhook_success/', views.stripe_webhook_payment_success, name='webhook_payment_success'),
]

submissions/urls.py
from django.urls import path
from . import views

app_name = 'submissions'
urlpatterns = [
    path('submission/recruiting/', views.handle_recruiting_submissions, name='recruiting_submission'),
    path('submission/tours/', views.handle_tours_submissions, name='tours_submission'),
    path('submission/team-item/', views.handle_team_item_submissions, name='team_item_submission'),
    path('submission/issue/', views.handle_issue_submission, name='issue'),
    path('submission/feedback/', views.handle_feedback_submission, name='feedback'),
    path('submission/design/', views.handle_design_submission, name='design'),
    path('submission/specialist/', views.handle_specialist_submission, name='specialist'),
    path('success/<str:message>/', views.success_page, name='success'),
]

firstfive/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}f5{% endblock %}</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'media/index/favicon.ico' %}" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap" rel="stylesheet">

    {% block extra_head %}{% endblock %}
</head>
<body>
    <nav class="navigation-bar">
        <div class="nav-content-wrapper">
            <div class="logo-wrapper">
                <a href="{% url 'f5index:home' %}"><img src="{% static 'media/index/firstfive-logo.png' %}" /></a>
            </div>
            <a class="navigation-link" href="{% url 'f5index:home' %}">Home</a>
            <a class="navigation-link" href="{% url 'f5index:about' %}">About</a>
            <a class="navigation-link" href="{% url 'store:store' %}">Store</a>
            <a class="navigation-link" href="{% url 'f5index:services' %}">Services</a>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <div class="footer">
        <div class="footer-starter-wrapper">
            <div class="footer-notice">*This platform is under live maintenance and is updated weekly. If something does not work, please <a class="footer-help-link" href="{% url 'submissions:issue' %}">report it</a> here.</div>
            <div class="footer-title">First Five Rugby 2024</div>
        </div>
        <div class="footer-wrapper">
            <div class="footer-column">
            <div class="column-label">Player Services</div>
            <ul class="column-list">
                <li><a class="footer-column-link" href="#">Fitness Plans</a></li>
                <li><a class="footer-column-link" href="#">Diet Plans</a></li>
                <li><a class="footer-column-link" href="#">Play Abroad</a></li>
                <li><a class="footer-column-link" href="#">Free Evaluation</a></li>
            </ul>
        </div>
        <div class="footer-column">
            <div class="column-label">Team Services</div>
            <ul class="column-list">
                <li><a class="footer-column-link" href="#">Custom Team Kit</a></li>
                <li><a class="footer-column-link" href="#">Recruiting Service</a></li>
                <li><a class="footer-column-link" href="#">Social Media Plan</a></li>
                <li><a class="footer-column-link" href="#">Team Tours</a></li>
            </ul>
        </div>
        <div class="footer-column">
            <div class="column-label">Careers</div>
            <ul class="column-list">
                <li><a class="footer-column-link" href="#">All Positions</a></li>
                <li><a class="footer-column-link" href="#">Strength and Fitness</a></li>
                <li><a class="footer-column-link" href="#">Diet & Nutrition</a></li>
                <li><a class="footer-column-link" href="#">Rugby Coaching</a></li>
            </ul>
        </div>
        <div class="footer-column">
            <div class="column-label">Contact</div>
            <ul class="column-list">
                <li><a class="footer-column-link" href="{% url 'submissions:feedback' %}">Leave Feedback</a></li>
                <li><a class="footer-column-link" href="#">Send Email</a></li>
                <li><a class="footer-column-link" href="#">FAQ</a></li>
            </ul>
        </div>
        </div>
    </div>
</body>
</html>